/* tslint:disable */
/* eslint-disable */
/**
 * People in Need - Springboard Service
 * This backend is meant to be a simple CRUD service for supporting  collaboration between organizations and the beneficiaries supported by them.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ActivityStatus = {
  InProgress: "IN_PROGRESS",
  Completed: "COMPLETED",
} as const;
export type ActivityStatus =
  (typeof ActivityStatus)[keyof typeof ActivityStatus];

export function ActivityStatusFromJSON(json: any): ActivityStatus {
  return ActivityStatusFromJSONTyped(json, false);
}

export function ActivityStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ActivityStatus {
  return json as ActivityStatus;
}

export function ActivityStatusToJSON(value?: ActivityStatus | null): any {
  return value as any;
}
