/* tslint:disable */
/* eslint-disable */
/**
 * People in Need - Springboard Service
 * This backend is meant to be a simple CRUD service for supporting  collaboration between organizations and the beneficiaries supported by them.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BeneficiaryCreationRequest
 */
export interface BeneficiaryCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryCreationRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryCreationRequest
     */
    lastName?: string;
    /**
     * 
     * @type {Date}
     * @memberof BeneficiaryCreationRequest
     */
    dateOfBirth?: Date;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryCreationRequest
     */
    identity?: string;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryCreationRequest
     */
    phoneNumber?: string;
    /**
     * 
     * @type {number}
     * @memberof BeneficiaryCreationRequest
     */
    cabinNumber?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof BeneficiaryCreationRequest
     */
    needs?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryCreationRequest
     */
    comments?: string;
}

/**
 * Check if a given object implements the BeneficiaryCreationRequest interface.
 */
export function instanceOfBeneficiaryCreationRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BeneficiaryCreationRequestFromJSON(json: any): BeneficiaryCreationRequest {
    return BeneficiaryCreationRequestFromJSONTyped(json, false);
}

export function BeneficiaryCreationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeneficiaryCreationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'dateOfBirth': !exists(json, 'dateOfBirth') ? undefined : (new Date(json['dateOfBirth'])),
        'identity': !exists(json, 'identity') ? undefined : json['identity'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'cabinNumber': !exists(json, 'cabinNumber') ? undefined : json['cabinNumber'],
        'needs': !exists(json, 'needs') ? undefined : json['needs'],
        'comments': !exists(json, 'comments') ? undefined : json['comments'],
    };
}

export function BeneficiaryCreationRequestToJSON(value?: BeneficiaryCreationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'lastName': value.lastName,
        'dateOfBirth': value.dateOfBirth === undefined ? undefined : (value.dateOfBirth.toISOString()),
        'identity': value.identity,
        'phoneNumber': value.phoneNumber,
        'cabinNumber': value.cabinNumber,
        'needs': value.needs,
        'comments': value.comments,
    };
}

