/* tslint:disable */
/* eslint-disable */
/**
 * People in Need - Springboard Service
 * This backend is meant to be a simple CRUD service for supporting  collaboration between organizations and the beneficiaries supported by them.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface NeedCreationRequest
 */
export interface NeedCreationRequest {
  /**
   *
   * @type {string}
   * @memberof NeedCreationRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof NeedCreationRequest
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof NeedCreationRequest
   */
  alternativeName?: string;
}

/**
 * Check if a given object implements the NeedCreationRequest interface.
 */
export function instanceOfNeedCreationRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function NeedCreationRequestFromJSON(json: any): NeedCreationRequest {
  return NeedCreationRequestFromJSONTyped(json, false);
}

export function NeedCreationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): NeedCreationRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    description: !exists(json, "description") ? undefined : json["description"],
    alternativeName: !exists(json, "alternativeName")
      ? undefined
      : json["alternativeName"],
  };
}

export function NeedCreationRequestToJSON(
  value?: NeedCreationRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    description: value.description,
    alternativeName: value.alternativeName,
  };
}
