/* tslint:disable */
/* eslint-disable */
/**
 * People in Need - Springboard Service
 * This backend is meant to be a simple CRUD service for supporting  collaboration between organizations and the beneficiaries supported by them.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationCreationRequest
 */
export interface OrganizationCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreationRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreationRequest
     */
    streetAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreationRequest
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreationRequest
     */
    zipcode?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreationRequest
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreationRequest
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OrganizationCreationRequest
     */
    needs?: Array<string>;
}

/**
 * Check if a given object implements the OrganizationCreationRequest interface.
 */
export function instanceOfOrganizationCreationRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganizationCreationRequestFromJSON(json: any): OrganizationCreationRequest {
    return OrganizationCreationRequestFromJSONTyped(json, false);
}

export function OrganizationCreationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationCreationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'streetAddress': !exists(json, 'streetAddress') ? undefined : json['streetAddress'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'zipcode': !exists(json, 'zipcode') ? undefined : json['zipcode'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'needs': !exists(json, 'needs') ? undefined : json['needs'],
    };
}

export function OrganizationCreationRequestToJSON(value?: OrganizationCreationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'streetAddress': value.streetAddress,
        'state': value.state,
        'zipcode': value.zipcode,
        'phoneNumber': value.phoneNumber,
        'description': value.description,
        'needs': value.needs,
    };
}

