/* tslint:disable */
/* eslint-disable */
/**
 * People in Need - Springboard Service
 * This backend is meant to be a simple CRUD service for supporting  collaboration between organizations and the beneficiaries supported by them.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OutcomeEvent = {
    FoundPermanentHousing: 'Found Permanent Housing',
    Incarcerated: 'Incarcerated',
    Deceased: 'Deceased',
    AssertiveCommunity: 'Assertive Community',
    LongTermSubstanceAbuseTreatment: 'Long-term Substance Abuse Treatment',
    RuleViolations: 'Rule Violations',
    BankAccountOpened: 'Bank Account Opened',
    Ged: 'GED',
    FoundEmplovment: 'Found Emplovment',
    TrainingProgram: 'Training Program',
    Other: 'Other'
} as const;
export type OutcomeEvent = typeof OutcomeEvent[keyof typeof OutcomeEvent];


export function OutcomeEventFromJSON(json: any): OutcomeEvent {
    return OutcomeEventFromJSONTyped(json, false);
}

export function OutcomeEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutcomeEvent {
    return json as OutcomeEvent;
}

export function OutcomeEventToJSON(value?: OutcomeEvent | null): any {
    return value as any;
}

